SistemaControleVendasProjeto/Controllers/Nivel2Controller.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VendasProjeto.Data;

namespace SistemaControleVendasProjeto.Controllers
{
    public class Nivel2Controller : Controller
    {
        private readonly SistemaControleVendasProjetoContext _context;

        public Nivel2Controller(SistemaControleVendasProjetoContext context)
        {
            _context = context;
        }

        // GET: Nivel2
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pedido.ToListAsync());
        }

        // GET: Nivel2/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedido.FirstOrDefaultAsync(m => m.PedidoID == id);

            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }
    }
}

SistemaControleVendasProjeto/Views/Nivel2/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model SistemaControleVendasProjeto.Models.Pedido

<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Controle de Vendas</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Política de Privacidade</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Nivel2" asp-action="Index">Vendas</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</header>

<h1>Detalhes do Pedido</h1>

<dl class="row">
    <dt class="col-sm-2">ID do Pedido:</dt>
    <dd class="col-sm-10">@Model.PedidoID</dd>

    <dt class="col-sm-2">ID do Cliente:</dt>
    <dd class="col-sm-10">@Model.ClienteID</dd>

    <dt class="col-sm-2">ID do Funcionário:</dt>
    <dd class="col-sm-10">@Model.FuncionarioID</dd>


</dl>

<div class="form-group">
    <a asp-action="Index" class="btn btn-info">Voltar para a Lista</a>
</div>

SistemaControleVendasProjeto/Views/Nivel2/Index.cshtml
@model IEnumerable<SistemaControleVendasProjeto.Models.Pedido>

<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Controle de Vendas</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Política de Privacidade</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Nivel2" asp-action="Index">Vendas</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</header>

<h1>Vendas</h1>

<table class="table">
    <thead>
        <tr>
            <th>ID do Pedido</th>
            <th>ID do Cliente</th>
            <th>ID do Funcionário</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var pedido in Model)
        {
            <tr>
                <td>@pedido.PedidoID</td>
                <td>@pedido.ClienteID</td>
                <td>@pedido.FuncionarioID</td>
                <td>

                    <div class="form-group">
                        <a asp-action="Details" asp-route-id="@pedido.PedidoID" class="btn btn-info">Detalhes</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>